# Generated by Django 5.2.8 on 2025-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drone_images/')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('vari', models.FloatField(blank=True, null=True)),
                ('gli', models.FloatField(blank=True, null=True)),
                ('exg', models.FloatField(blank=True, null=True)),
                ('canopy_cover', models.FloatField(blank=True, null=True)),
                ('stress_percentage', models.FloatField(blank=True, null=True)),
                ('yield_estimate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
