# Generated by Django 5.2.8 on 2025-11-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneimage',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='droneimage',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='droneimage',
            name='lon',
        ),
    ]
