# Generated by Django 5.2.8 on 2025-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_droneimage_altitude_remove_droneimage_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='droneimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
