# Generated by Django 5.2.8 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_droneimage_image_alter_droneimage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneimage',
            name='image',
            field=models.ImageField(default='', upload_to='drone_images/'),
            preserve_default=False,
        ),
    ]
