# Generated by Django 5.2.8 on 2025-12-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_droneimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avg_canopy_cover', models.FloatField(blank=True, null=True)),
                ('avg_stress_percentage', models.FloatField(blank=True, null=True)),
                ('avg_yield_estimate', models.FloatField(blank=True, null=True)),
                ('avg_vari', models.FloatField(blank=True, null=True)),
                ('avg_gli', models.FloatField(blank=True, null=True)),
                ('avg_exg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='droneimage',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.analysissession'),
            preserve_default=False,
        ),
    ]
