# Generated by Django 5.2.8 on 2025-12-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysissession_droneimage_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_exg',
            new_name='canopy_cover',
        ),
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_canopy_cover',
            new_name='exg',
        ),
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_gli',
            new_name='gli',
        ),
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_stress_percentage',
            new_name='stress_percentage',
        ),
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_vari',
            new_name='vari',
        ),
        migrations.RenameField(
            model_name='analysissession',
            old_name='avg_yield_estimate',
            new_name='yield_estimate',
        ),
    ]
